Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "Server1",
          :box => "bento/ubuntu-20.04",
          :ip => "192.168.14.170",
        },
        {
          :hostname => "Server2",
          :box => "bento/ubuntu-20.04",
          :ip => "192.168.14.171",
        },
	{
          :hostname => "Server3",
          :box => "bento/ubuntu-20.04",
          :ip => "192.168.14.172",
        },
      
      ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :public_network, ip: machine[:ip]
                                    
            node.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", 1024]
                vb.customize ["modifyvm", :id, "--cpus", 1]
            end
        end
    end
end
